TemplateExam/TemplateExam/TemplateApp/urls.py
from django.urls import path
from . import views


app_name = "app"
urlpatterns = [
    path("home", views.home, name="home"),
    path("members", views.members, name="members"),
    path("member/<int:id>", views.member, name="member"),
]

TemplateExam/TemplateExam/TemplateExam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("app/", include("TemplateApp.urls")),
]

TemplateExam/TemplateExam/TemplateApp/models.py
from django.db import models

# Create your models here.

TemplateExam/TemplateExam/TemplateApp/views.py
from django.shortcuts import render

# Create your views here.


class Member:
    def __init__(self, id, name, join_at, picture_path):
        self.id = id
        self.name = name
        self.join_at = join_at
        self.picture_path = picture_path


member_list = [
    Member(0, "King_Krull", "2020/04/01", "img/king_krull.jpeg"),
    Member(1, "Enguarde", "2021/04/01", "img/enguarde.jpeg"),
    Member(2, "Very_Gnawty", "2022/05/01", "img/very_Gnawty.jpeg"),
    Member(3, "Squawks", "2019/06/01", "img/squawks.jpeg"),
]
# ホーム画面
def home(request):
    return render(request, "home.html")


# メンバー一覧
def members(request):
    return render(request, "members.html", context={"members": member_list})


# メンバーの画面詳細
def member(request, id):
    return render(request, "member_detail.html", context={"member": member_list[id]})

TemplateExam/TemplateExam/templates/base.html
<DOCTYPE html>
  <html>
    <head>
      <meta charset"utf-8">
      <title>
        {% block title %}愉快なドンキーコングのキャラクターたち{% endblock %}
      </title>
      <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
        crossorigin="anonymous"
      />
    </head>
    <body>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url "app:home" %}">Home</a>
        <a class="navbar-brand" href="{% url "app:members" %}">キャラクター一覧</a>
      </nav>
      {% block content %}{% endblock %}
    </body>
  </html>
</DOCTYPE>

TemplateExam/TemplateExam/templates/home.html
{% extends "base.html" %} {% block title %}ホーム{{ block.super }}{% endblock %}
{% block content %}
<p>愉快なドンキーコングのキャラクターたち</p>
{% endblock %}

TemplateExam/TemplateExam/templates/member_detail.html
{% extends "base.html" %} {% block title %} キャラクター詳細{{ block.super }}{%
endblock %} {% block content %} {% load static %}
<h1>キャラクター詳細画面</h1>
<img src="{% static member.picutre_path %}" />
<p>名前: {{ member.name }}</p>
<p>参加日: {{ member.join_at }}</p>
{% endfor %} {% endblock %}

TemplateExam/TemplateExam/templates/members.html
{% extends "base.html" %}{% block title %}キャラクター一覧{{ block.super }}{% endblock %}
{% block content %} {% for member in members %}
<p><a href="{% url "app:member" id=member.id %}"</p>
{% endfor %} {% endblock %}

TemplateExam/templates/home.html
{% extends "base.html" %} {% block title %}ホーム{{ block.super }}{% endblock%}
{% block content %}
<p>愉快なドンキーコングのキャラクターたち</p>
{% endblock %}