TemplateSample/TemplateApp/urls.py
from django.urls import path
from . import views


app_name = "template_app"
urlpatterns = [
    path("", views.index, name="index"),
    path("home/<first_name>/<last_name>", views.home, name="home"),
    path("sample1", views.sample1, name="sample1"),
    path("sample2", views.sample2, name="sample2"),
    path("sample3", views.sample3, name="sample3"),
    path("sample", views.sample, name="sample"),
]

TemplateSample/TemplateProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("template_app/", include("TemplateApp.urls")),
]

TemplateSample/TemplateApp/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    val = "Come on!"
    return render(request, "TemplateApp/index.html", context={"value": val})


def home(request, first_name, last_name):
    my_name = f"{ first_name }{ last_name }"
    # my_name = "aa"
    favorite_fruits = ["Apple", "Grape", "Lemon"]
    my_info = {"name": "Sota", "age": 11}
    status = 30
    return render(
        request,
        "home.html",
        context={
            "my_name": my_name,
            "favorite_fruits": favorite_fruits,
            "my_info": my_info,
            "status": status,
        },
    )


def sample1(request):
    return render(request, "sample1.html")


def sample2(request):
    return render(request, "sample2.html")


def sample(request):
    name = "Tatsuya Anegawa"
    height = 185
    weight = 76
    bmi = weight / (height / 100) ** 2
    page_url = "ホームページ: https://www.google.com"
    favorite_fruits = ["Apple", "Grape", "Lemon"]
    msg = """
    my name is
    Tatsuya
    """
    msg2 = "1234567890"
    return render(
        request,
        "sample.html",
        context={
            "name": name,
            "bmi": bmi,
            "page_url": page_url,
            "fruits": favorite_fruits,
            "msg": msg,
            "msg2": msg2,
        },
    )


class Country:
    """インスタンスのプロパティをtemplateに渡して画面上に表示"""

    def __init__(self, name, population, capital):
        self.name = name
        self.population = population
        self.capital = capital


def sample3(request):
    country = Country("Japan", 100000000, "Tokyo")
    return render(request, "sample3.html", context={"country": country})

TemplateSample/TemplateApp/templates/app/index.html
<h1>Hello World</h1>

TemplateSample/templates/base.html
<!--継承元のhtmlファイル-->
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <!--継承先で定義することができる-->
        <title>{% block title %}My Page{% endblock %}</title>
    </head>
    <body>
        <h1>My Page</h1>
        {% block content %}{% endblock %}
</html>

TemplateSample/templates/home.html
{% load event_tags %}
<h1>Name: {{ my_name }}</h1>
<h2>果物: {{ favorite_fruits.2 }}</h2>
<h3>Age: {{ my_info.age }}</h3>
{{ my_name }}

<ul>
  {% for fruit in favorite_fruits %}
  <li>{{ fruit }}</li>
  {% endfor %}
</ul>

{% if "Grape" in favorite_fruits %}
<p>Grapeありますよ</p>
{% elif "Lemon" in favorite_fruits %}
<p>Lemomありますね</p>
{% else %}
<p>どれも買えませんでした。。</p>
<p>Not Found</p>
{% endif %} {% if "age" in my_info %}
<p>age in my_info</p>
{% if my_info.age < 20 %}
<p>未成年ですね</p>
{% endif %} {% endif %} {% if my_info.name == "Sota" %}
<p>Sotaだよ</p>
{% endif %}

<p>{{ status | status_to_string:"AAA" }}</p>

TemplateSample/templates/index.html
<h1>Good Night!</h1>
<p>{{value}}</p>

TemplateSample/templates/sample.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static "home.css" %}"
{# フィルター関数 #}
<h1>{{ name | upper }}</h1>
<h1>{{ page_url | urlize }}</h1>
<p>BMI: {{ bmi | floatformat:2 }}</p>
<p>給料: {{ salary | default:"秘密だよ" }}</p>
<p>{{ fruits | random | lower }}</p>
<p>{{ fruits | join:", "}}</p>
<p>{{ msg | linebreaks }}</p>
<p>{{ msg2 | truncatechars:7 }}</p>

{% filter upper %}
<p>aaa</p>
<h1>bbb</h1>
{% endfilter %}

<a href = "{% url "template_app:home" first_name="Sota" last_name="Anegawa" %}">home</a>

<img src="{% static "donkey_kong.jpeg" %}">

TemplateSample/templates/sample1.html
{% extends "base.html" %} {% block title %}Sample1 {{block.super}}{% endblock %}
{% block content %}
<p>Sample1</p>
{% endblock %}

TemplateSample/templates/sample2.html
{% extends "base.html" %}
{% block title %}Sample2 {{block.super}}{% endblock %}
{% block content %}
<p>Sample2</p>
{% endblock %}

TemplateSample/templates/sample3.html
国名: {{ country.name }}<br />
人口: {{ country.population }}<br />
首都: {{ country.capital }}